### ISSUE TITLE
Promise at Send

### ISSUE THREAD

**Issue by jackdaddy69** [1oginov/Web-Bluetooth-Terminal#10]
The promise returned by the send command should be at the end when all the data has been sent.  The promise returned only is the first chunk I believe.  I use this to set a flag that tells me I cant send anymore data until the previous data is complete, and this bombs since data collides.  Please fix.  Thx.

**Comment by 1oginov** [comment]
Send returns chained Promise that will be fulfilled when all chucks sent: https://github.com/1oginov/Web-Bluetooth-Terminal/blob/master/js/BluetoothTerminal.js#L166

**Comment by jackdaddy69** [comment]
Well then shouldnt:
terminal.send('first part').then(terminal.send('second part'))
work?
I get an error on Linux or chromebooks
NetworkError: GATT operation already in progress

So how can I send data back to back, without resorting to timers?

**Comment by loginov-rocks** [comment]
Did you mean:

```js
terminal.send('first part').then(() => terminal.send('second part')).then(() => {
 // first and second part has been sent, further actions here...
})
```

Promises were introduced in https://github.com/loginov-rocks/bluetooth-terminal/commit/f21d43a2fa88cabf573af6131f1514f546b0444c so you can try to install old version of bluetooth-terminal maybe this will help. If yes, I'll consider to move to the timeouts...
