### ISSUE TITLE
Реализация загрузчика для Atmel

### ISSUE THREAD

**Issue by dmitryshagin** [1oginov/Web-Bluetooth-Terminal#3]
На уровне идеи - если прикрутить к этому восхотительному приложению реализацию какого-нибудь относительно стандартного протокола загрузчика (типа того протокола, что реализует, например, avrprog), то получится ещё отличная возможность обновлять прошивку в девайсах по блутусу. Ну это так, мечты :) Спасибо за приложение, пригодится!

**Comment by 1oginov** [comment]
Привет, @dmitryshagin!

**Comment by dmitryshagin** [comment]
Понятно, спасибо. Может поковыряться, если будет вдохновение )
