### ISSUE TITLE
bluetooth module serial question

### ISSUE THREAD

**Issue by jeryfast** [1oginov/Web-Bluetooth-Terminal#5]
Hello,

great job, I am looking for something similar. Is this solution compatible with serial bluetooth modules like hc-04 and hc-12? Is it possible for hc-12 to communicate with ble devices?

Regards
Jernej

**Comment by 1oginov** [comment]
Hi @jeryfast !

Do HC-04 and HC-12 support Bluetooth 4+? It seems they don't, while Web Bluetooth API can only communicate with Bluetooth 4+
